apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heureum-ingress
  namespace: heureum
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - DOMAIN_PLACEHOLDER
        - www.DOMAIN_PLACEHOLDER
      secretName: heureum-tls
  rules:
    - host: DOMAIN_PLACEHOLDER
      http:
        paths:
          - path: /(api/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: heureum-platform
                port:
                  number: 8001
          - path: /(v1/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: heureum-platform
                port:
                  number: 8001
          - path: /(_allauth/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: heureum-platform
                port:
                  number: 8001
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: heureum-frontend
                port:
                  number: 80
